name: Move linked issue to "In Review" when PR is opened

on:
  pull_request:
    types: [opened, reopened]

jobs:
  move-linked-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to 'In Review'
        uses: peter-evans/create-or-update-project-card@v3
        with:
          token: ${{ secrets.ORG_PAT }}
          project-location: organization
          project-name: 'InnmobiliariaOficial_365Soft'
          column-name: 'In Review'
          issue-number: ${{ github.event.pull_request.number }}
