name: Move linked issue to "In Review" when PR is opened

on:
  pull_request:
    types: [opened, reopened]

jobs:
  move-linked-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to 'In Review'
        uses: titoportas/update-project-fields@v1
        with:
          token: ${{ secrets.ORG_PAT }} # tu token con permisos repo, project, workflow
          project-url: https://github.com/orgs/365Soft-Bolivia/projects/1
          field: Status
          value: In review
